/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StoreRouteRouteImport } from './routes/store/route'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteRouteImport } from './routes/admin/dashboard/route'
import { Route as StoreJewelryIndexRouteImport } from './routes/store/jewelry/index'
import { Route as StoreCatalogIndexRouteImport } from './routes/store/catalog/index'
import { Route as StoreCartIndexRouteImport } from './routes/store/cart/index'
import { Route as ProfileOrdersIndexRouteImport } from './routes/profile/orders/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as ProfileOrdersOrderIdRouteImport } from './routes/profile/orders/$orderId'
import { Route as AdminDashboardOrdersRouteImport } from './routes/admin/dashboard/orders'
import { Route as StoreCatalogJewelryIndexRouteImport } from './routes/store/catalog/jewelry/index'
import { Route as StoreCatalogHatsIndexRouteImport } from './routes/store/catalog/hats/index'
import { Route as AdminDashboardUsersIndexRouteImport } from './routes/admin/dashboard/users/index'
import { Route as AdminDashboardProductsIndexRouteImport } from './routes/admin/dashboard/products/index'
import { Route as AdminDashboardUsersUserIdRouteImport } from './routes/admin/dashboard/users/$userId'
import { Route as AdminDashboardProductsNewRouteImport } from './routes/admin/dashboard/products/new'
import { Route as StoreCatalogProductsJeweleryIdRouteImport } from './routes/store/catalog/products/jewelery/$id'
import { Route as StoreCatalogProductsHatsIdRouteImport } from './routes/store/catalog/products/hats/$id'
import { Route as AdminDashboardProductsEditProductIdRouteImport } from './routes/admin/dashboard/products/edit.$productId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRouteRoute = StoreRouteRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StoreJewelryIndexRoute = StoreJewelryIndexRouteImport.update({
  id: '/jewelry/',
  path: '/jewelry/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreCatalogIndexRoute = StoreCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreCartIndexRoute = StoreCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const ProfileOrdersIndexRoute = ProfileOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const ProfileOrdersOrderIdRoute = ProfileOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const AdminDashboardOrdersRoute = AdminDashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const StoreCatalogJewelryIndexRoute =
  StoreCatalogJewelryIndexRouteImport.update({
    id: '/catalog/jewelry/',
    path: '/catalog/jewelry/',
    getParentRoute: () => StoreRouteRoute,
  } as any)
const StoreCatalogHatsIndexRoute = StoreCatalogHatsIndexRouteImport.update({
  id: '/catalog/hats/',
  path: '/catalog/hats/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const AdminDashboardUsersIndexRoute =
  AdminDashboardUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardProductsIndexRoute =
  AdminDashboardProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardUsersUserIdRoute =
  AdminDashboardUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardProductsNewRoute =
  AdminDashboardProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const StoreCatalogProductsJeweleryIdRoute =
  StoreCatalogProductsJeweleryIdRouteImport.update({
    id: '/catalog/products/jewelery/$id',
    path: '/catalog/products/jewelery/$id',
    getParentRoute: () => StoreRouteRoute,
  } as any)
const StoreCatalogProductsHatsIdRoute =
  StoreCatalogProductsHatsIdRouteImport.update({
    id: '/catalog/products/hats/$id',
    path: '/catalog/products/hats/$id',
    getParentRoute: () => StoreRouteRoute,
  } as any)
const AdminDashboardProductsEditProductIdRoute =
  AdminDashboardProductsEditProductIdRouteImport.update({
    id: '/products/edit/$productId',
    path: '/products/edit/$productId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/store/': typeof StoreIndexRoute
  '/admin/dashboard/orders': typeof AdminDashboardOrdersRoute
  '/profile/orders/$orderId': typeof ProfileOrdersOrderIdRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/profile/orders/': typeof ProfileOrdersIndexRoute
  '/store/cart/': typeof StoreCartIndexRoute
  '/store/catalog/': typeof StoreCatalogIndexRoute
  '/store/jewelry/': typeof StoreJewelryIndexRoute
  '/admin/dashboard/products/new': typeof AdminDashboardProductsNewRoute
  '/admin/dashboard/users/$userId': typeof AdminDashboardUsersUserIdRoute
  '/admin/dashboard/products/': typeof AdminDashboardProductsIndexRoute
  '/admin/dashboard/users/': typeof AdminDashboardUsersIndexRoute
  '/store/catalog/hats/': typeof StoreCatalogHatsIndexRoute
  '/store/catalog/jewelry/': typeof StoreCatalogJewelryIndexRoute
  '/admin/dashboard/products/edit/$productId': typeof AdminDashboardProductsEditProductIdRoute
  '/store/catalog/products/hats/$id': typeof StoreCatalogProductsHatsIdRoute
  '/store/catalog/products/jewelery/$id': typeof StoreCatalogProductsJeweleryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/store': typeof StoreIndexRoute
  '/admin/dashboard/orders': typeof AdminDashboardOrdersRoute
  '/profile/orders/$orderId': typeof ProfileOrdersOrderIdRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/profile/orders': typeof ProfileOrdersIndexRoute
  '/store/cart': typeof StoreCartIndexRoute
  '/store/catalog': typeof StoreCatalogIndexRoute
  '/store/jewelry': typeof StoreJewelryIndexRoute
  '/admin/dashboard/products/new': typeof AdminDashboardProductsNewRoute
  '/admin/dashboard/users/$userId': typeof AdminDashboardUsersUserIdRoute
  '/admin/dashboard/products': typeof AdminDashboardProductsIndexRoute
  '/admin/dashboard/users': typeof AdminDashboardUsersIndexRoute
  '/store/catalog/hats': typeof StoreCatalogHatsIndexRoute
  '/store/catalog/jewelry': typeof StoreCatalogJewelryIndexRoute
  '/admin/dashboard/products/edit/$productId': typeof AdminDashboardProductsEditProductIdRoute
  '/store/catalog/products/hats/$id': typeof StoreCatalogProductsHatsIdRoute
  '/store/catalog/products/jewelery/$id': typeof StoreCatalogProductsJeweleryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/store/': typeof StoreIndexRoute
  '/admin/dashboard/orders': typeof AdminDashboardOrdersRoute
  '/profile/orders/$orderId': typeof ProfileOrdersOrderIdRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/profile/orders/': typeof ProfileOrdersIndexRoute
  '/store/cart/': typeof StoreCartIndexRoute
  '/store/catalog/': typeof StoreCatalogIndexRoute
  '/store/jewelry/': typeof StoreJewelryIndexRoute
  '/admin/dashboard/products/new': typeof AdminDashboardProductsNewRoute
  '/admin/dashboard/users/$userId': typeof AdminDashboardUsersUserIdRoute
  '/admin/dashboard/products/': typeof AdminDashboardProductsIndexRoute
  '/admin/dashboard/users/': typeof AdminDashboardUsersIndexRoute
  '/store/catalog/hats/': typeof StoreCatalogHatsIndexRoute
  '/store/catalog/jewelry/': typeof StoreCatalogJewelryIndexRoute
  '/admin/dashboard/products/edit/$productId': typeof AdminDashboardProductsEditProductIdRoute
  '/store/catalog/products/hats/$id': typeof StoreCatalogProductsHatsIdRoute
  '/store/catalog/products/jewelery/$id': typeof StoreCatalogProductsJeweleryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/profile'
    | '/store'
    | '/about'
    | '/login'
    | '/logout'
    | '/register'
    | '/test'
    | '/admin/dashboard'
    | '/admin/'
    | '/profile/'
    | '/store/'
    | '/admin/dashboard/orders'
    | '/profile/orders/$orderId'
    | '/admin/dashboard/'
    | '/profile/orders/'
    | '/store/cart/'
    | '/store/catalog/'
    | '/store/jewelry/'
    | '/admin/dashboard/products/new'
    | '/admin/dashboard/users/$userId'
    | '/admin/dashboard/products/'
    | '/admin/dashboard/users/'
    | '/store/catalog/hats/'
    | '/store/catalog/jewelry/'
    | '/admin/dashboard/products/edit/$productId'
    | '/store/catalog/products/hats/$id'
    | '/store/catalog/products/jewelery/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/logout'
    | '/register'
    | '/test'
    | '/admin'
    | '/profile'
    | '/store'
    | '/admin/dashboard/orders'
    | '/profile/orders/$orderId'
    | '/admin/dashboard'
    | '/profile/orders'
    | '/store/cart'
    | '/store/catalog'
    | '/store/jewelry'
    | '/admin/dashboard/products/new'
    | '/admin/dashboard/users/$userId'
    | '/admin/dashboard/products'
    | '/admin/dashboard/users'
    | '/store/catalog/hats'
    | '/store/catalog/jewelry'
    | '/admin/dashboard/products/edit/$productId'
    | '/store/catalog/products/hats/$id'
    | '/store/catalog/products/jewelery/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/profile'
    | '/store'
    | '/about'
    | '/login'
    | '/logout'
    | '/register'
    | '/test'
    | '/admin/dashboard'
    | '/admin/'
    | '/profile/'
    | '/store/'
    | '/admin/dashboard/orders'
    | '/profile/orders/$orderId'
    | '/admin/dashboard/'
    | '/profile/orders/'
    | '/store/cart/'
    | '/store/catalog/'
    | '/store/jewelry/'
    | '/admin/dashboard/products/new'
    | '/admin/dashboard/users/$userId'
    | '/admin/dashboard/products/'
    | '/admin/dashboard/users/'
    | '/store/catalog/hats/'
    | '/store/catalog/jewelry/'
    | '/admin/dashboard/products/edit/$productId'
    | '/store/catalog/products/hats/$id'
    | '/store/catalog/products/jewelery/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  StoreRouteRoute: typeof StoreRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/store/jewelry/': {
      id: '/store/jewelry/'
      path: '/jewelry'
      fullPath: '/store/jewelry/'
      preLoaderRoute: typeof StoreJewelryIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/catalog/': {
      id: '/store/catalog/'
      path: '/catalog'
      fullPath: '/store/catalog/'
      preLoaderRoute: typeof StoreCatalogIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/cart/': {
      id: '/store/cart/'
      path: '/cart'
      fullPath: '/store/cart/'
      preLoaderRoute: typeof StoreCartIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/profile/orders/': {
      id: '/profile/orders/'
      path: '/orders'
      fullPath: '/profile/orders/'
      preLoaderRoute: typeof ProfileOrdersIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/profile/orders/$orderId': {
      id: '/profile/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/profile/orders/$orderId'
      preLoaderRoute: typeof ProfileOrdersOrderIdRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/admin/dashboard/orders': {
      id: '/admin/dashboard/orders'
      path: '/orders'
      fullPath: '/admin/dashboard/orders'
      preLoaderRoute: typeof AdminDashboardOrdersRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/store/catalog/jewelry/': {
      id: '/store/catalog/jewelry/'
      path: '/catalog/jewelry'
      fullPath: '/store/catalog/jewelry/'
      preLoaderRoute: typeof StoreCatalogJewelryIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/catalog/hats/': {
      id: '/store/catalog/hats/'
      path: '/catalog/hats'
      fullPath: '/store/catalog/hats/'
      preLoaderRoute: typeof StoreCatalogHatsIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/admin/dashboard/users/': {
      id: '/admin/dashboard/users/'
      path: '/users'
      fullPath: '/admin/dashboard/users/'
      preLoaderRoute: typeof AdminDashboardUsersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/products/': {
      id: '/admin/dashboard/products/'
      path: '/products'
      fullPath: '/admin/dashboard/products/'
      preLoaderRoute: typeof AdminDashboardProductsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/users/$userId': {
      id: '/admin/dashboard/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/dashboard/users/$userId'
      preLoaderRoute: typeof AdminDashboardUsersUserIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/products/new': {
      id: '/admin/dashboard/products/new'
      path: '/products/new'
      fullPath: '/admin/dashboard/products/new'
      preLoaderRoute: typeof AdminDashboardProductsNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/store/catalog/products/jewelery/$id': {
      id: '/store/catalog/products/jewelery/$id'
      path: '/catalog/products/jewelery/$id'
      fullPath: '/store/catalog/products/jewelery/$id'
      preLoaderRoute: typeof StoreCatalogProductsJeweleryIdRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/catalog/products/hats/$id': {
      id: '/store/catalog/products/hats/$id'
      path: '/catalog/products/hats/$id'
      fullPath: '/store/catalog/products/hats/$id'
      preLoaderRoute: typeof StoreCatalogProductsHatsIdRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/admin/dashboard/products/edit/$productId': {
      id: '/admin/dashboard/products/edit/$productId'
      path: '/products/edit/$productId'
      fullPath: '/admin/dashboard/products/edit/$productId'
      preLoaderRoute: typeof AdminDashboardProductsEditProductIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
  }
}

interface AdminDashboardRouteRouteChildren {
  AdminDashboardOrdersRoute: typeof AdminDashboardOrdersRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardProductsNewRoute: typeof AdminDashboardProductsNewRoute
  AdminDashboardUsersUserIdRoute: typeof AdminDashboardUsersUserIdRoute
  AdminDashboardProductsIndexRoute: typeof AdminDashboardProductsIndexRoute
  AdminDashboardUsersIndexRoute: typeof AdminDashboardUsersIndexRoute
  AdminDashboardProductsEditProductIdRoute: typeof AdminDashboardProductsEditProductIdRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardOrdersRoute: AdminDashboardOrdersRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardProductsNewRoute: AdminDashboardProductsNewRoute,
  AdminDashboardUsersUserIdRoute: AdminDashboardUsersUserIdRoute,
  AdminDashboardProductsIndexRoute: AdminDashboardProductsIndexRoute,
  AdminDashboardUsersIndexRoute: AdminDashboardUsersIndexRoute,
  AdminDashboardProductsEditProductIdRoute:
    AdminDashboardProductsEditProductIdRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileOrdersOrderIdRoute: typeof ProfileOrdersOrderIdRoute
  ProfileOrdersIndexRoute: typeof ProfileOrdersIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileOrdersOrderIdRoute: ProfileOrdersOrderIdRoute,
  ProfileOrdersIndexRoute: ProfileOrdersIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

interface StoreRouteRouteChildren {
  StoreIndexRoute: typeof StoreIndexRoute
  StoreCartIndexRoute: typeof StoreCartIndexRoute
  StoreCatalogIndexRoute: typeof StoreCatalogIndexRoute
  StoreJewelryIndexRoute: typeof StoreJewelryIndexRoute
  StoreCatalogHatsIndexRoute: typeof StoreCatalogHatsIndexRoute
  StoreCatalogJewelryIndexRoute: typeof StoreCatalogJewelryIndexRoute
  StoreCatalogProductsHatsIdRoute: typeof StoreCatalogProductsHatsIdRoute
  StoreCatalogProductsJeweleryIdRoute: typeof StoreCatalogProductsJeweleryIdRoute
}

const StoreRouteRouteChildren: StoreRouteRouteChildren = {
  StoreIndexRoute: StoreIndexRoute,
  StoreCartIndexRoute: StoreCartIndexRoute,
  StoreCatalogIndexRoute: StoreCatalogIndexRoute,
  StoreJewelryIndexRoute: StoreJewelryIndexRoute,
  StoreCatalogHatsIndexRoute: StoreCatalogHatsIndexRoute,
  StoreCatalogJewelryIndexRoute: StoreCatalogJewelryIndexRoute,
  StoreCatalogProductsHatsIdRoute: StoreCatalogProductsHatsIdRoute,
  StoreCatalogProductsJeweleryIdRoute: StoreCatalogProductsJeweleryIdRoute,
}

const StoreRouteRouteWithChildren = StoreRouteRoute._addFileChildren(
  StoreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  StoreRouteRoute: StoreRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
