/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinalRouteImport } from './routes/final'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JewelryIndexRouteImport } from './routes/jewelry/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CatalogJewelryIndexRouteImport } from './routes/catalog/jewelry/index'
import { Route as CatalogHatsIndexRouteImport } from './routes/catalog/hats/index'
import { Route as CatalogProductsJeweleryIdRouteImport } from './routes/catalog/products/jewelery/$id'
import { Route as CatalogProductsHatsIdRouteImport } from './routes/catalog/products/hats/$id'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelryIndexRoute = JewelryIndexRouteImport.update({
  id: '/jewelry/',
  path: '/jewelry/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogJewelryIndexRoute = CatalogJewelryIndexRouteImport.update({
  id: '/catalog/jewelry/',
  path: '/catalog/jewelry/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogHatsIndexRoute = CatalogHatsIndexRouteImport.update({
  id: '/catalog/hats/',
  path: '/catalog/hats/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogProductsJeweleryIdRoute =
  CatalogProductsJeweleryIdRouteImport.update({
    id: '/catalog/products/jewelery/$id',
    path: '/catalog/products/jewelery/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalogProductsHatsIdRoute = CatalogProductsHatsIdRouteImport.update({
  id: '/catalog/products/hats/$id',
  path: '/catalog/products/hats/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/final': typeof FinalRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/catalog/': typeof CatalogIndexRoute
  '/jewelry/': typeof JewelryIndexRoute
  '/catalog/hats/': typeof CatalogHatsIndexRoute
  '/catalog/jewelry/': typeof CatalogJewelryIndexRoute
  '/catalog/products/hats/$id': typeof CatalogProductsHatsIdRoute
  '/catalog/products/jewelery/$id': typeof CatalogProductsJeweleryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/final': typeof FinalRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/catalog': typeof CatalogIndexRoute
  '/jewelry': typeof JewelryIndexRoute
  '/catalog/hats': typeof CatalogHatsIndexRoute
  '/catalog/jewelry': typeof CatalogJewelryIndexRoute
  '/catalog/products/hats/$id': typeof CatalogProductsHatsIdRoute
  '/catalog/products/jewelery/$id': typeof CatalogProductsJeweleryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/final': typeof FinalRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/catalog/': typeof CatalogIndexRoute
  '/jewelry/': typeof JewelryIndexRoute
  '/catalog/hats/': typeof CatalogHatsIndexRoute
  '/catalog/jewelry/': typeof CatalogJewelryIndexRoute
  '/catalog/products/hats/$id': typeof CatalogProductsHatsIdRoute
  '/catalog/products/jewelery/$id': typeof CatalogProductsJeweleryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/final'
    | '/login'
    | '/register'
    | '/test'
    | '/catalog/'
    | '/jewelry/'
    | '/catalog/hats/'
    | '/catalog/jewelry/'
    | '/catalog/products/hats/$id'
    | '/catalog/products/jewelery/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/final'
    | '/login'
    | '/register'
    | '/test'
    | '/catalog'
    | '/jewelry'
    | '/catalog/hats'
    | '/catalog/jewelry'
    | '/catalog/products/hats/$id'
    | '/catalog/products/jewelery/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/final'
    | '/login'
    | '/register'
    | '/test'
    | '/catalog/'
    | '/jewelry/'
    | '/catalog/hats/'
    | '/catalog/jewelry/'
    | '/catalog/products/hats/$id'
    | '/catalog/products/jewelery/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FinalRoute: typeof FinalRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TestRoute: typeof TestRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  JewelryIndexRoute: typeof JewelryIndexRoute
  CatalogHatsIndexRoute: typeof CatalogHatsIndexRoute
  CatalogJewelryIndexRoute: typeof CatalogJewelryIndexRoute
  CatalogProductsHatsIdRoute: typeof CatalogProductsHatsIdRoute
  CatalogProductsJeweleryIdRoute: typeof CatalogProductsJeweleryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewelry/': {
      id: '/jewelry/'
      path: '/jewelry'
      fullPath: '/jewelry/'
      preLoaderRoute: typeof JewelryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/jewelry/': {
      id: '/catalog/jewelry/'
      path: '/catalog/jewelry'
      fullPath: '/catalog/jewelry/'
      preLoaderRoute: typeof CatalogJewelryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/hats/': {
      id: '/catalog/hats/'
      path: '/catalog/hats'
      fullPath: '/catalog/hats/'
      preLoaderRoute: typeof CatalogHatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/products/jewelery/$id': {
      id: '/catalog/products/jewelery/$id'
      path: '/catalog/products/jewelery/$id'
      fullPath: '/catalog/products/jewelery/$id'
      preLoaderRoute: typeof CatalogProductsJeweleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/products/hats/$id': {
      id: '/catalog/products/hats/$id'
      path: '/catalog/products/hats/$id'
      fullPath: '/catalog/products/hats/$id'
      preLoaderRoute: typeof CatalogProductsHatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FinalRoute: FinalRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TestRoute: TestRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  JewelryIndexRoute: JewelryIndexRoute,
  CatalogHatsIndexRoute: CatalogHatsIndexRoute,
  CatalogJewelryIndexRoute: CatalogJewelryIndexRoute,
  CatalogProductsHatsIdRoute: CatalogProductsHatsIdRoute,
  CatalogProductsJeweleryIdRoute: CatalogProductsJeweleryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
